config/routes.rb
Rails.application.routes.draw do
  get 'top' => 'homes#top'
  resources :lists
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    has_one_attached :image
    #Listモデルに画像を扱うためのimageカラム追記（されたかのよう？）

    validates :title, presence: true
    validates :body, presence: true
    validates :image, presence: true
    #validatesで項目指定⇒presence（存在）をチェック
    #入力が無ければ投稿できない状態にする
    #imageの処理は、active_storage導入前に画像添付がない場合の対処。presenceをチェックしても問題なし。

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    #新規作成のフォームを表示するためのインスタンス
    @list = List.new
    #インスタンス変数：コントローラー⇒Viewでデータの受け渡しができる、@マークをつけて定義
    #ローカル変数 ：受け渡しできない、何もつけない

  end

  def create
    #データを受け取り新規保存するためのインスタンス作成
    @list = List.new(list_params) 
    #データをデータベースに保存するためのsaveメソッド実行
    if @list.save
    #保存できる場合、保存したデータの詳細画面へのリダイレクト
      redirect_to list_path(@list.id)
    else
    #保存できなければ、新規投稿ページを再表示
    #render:同じコントローラ内の別アクションのViewを表示
      render :new
    end
  end

  def index
    #データベース内の保存データを全取得するためのインスタンス
    @lists = List.all
    #インスタンス変数（viewファイルで情報表示するため）
  end 

  def show
    #引数を受け取り、URLの:idのレコードを取得するためのインスタンス
    @list = List.find(params[:id])
    #レコード1件のみ取得するため単数形
  end

  def edit
    #説明はshow参照
    @list = List.find(params[:id])
  end

  def update
    #引数を受け取り、レコード取得
    list = List.find(params[:id])
    #データを更新するためのupdateメソッド
    list.update(list_params)
    #一覧へのリダイレクト
    redirect_to list_path(list.id)
  end

  def destroy
    #データを1件取得
    list = List.find(params[:id])
    #取得したデータを削除
    list.destroy
    #投稿一覧へリダイレクト
    redirect_to '/lists'
  end

  private
  #ここから下はcontrollerの中でしか呼び出せない（境界線）。データベースにアクセスするアクション、viewに表示するアクション等を下に書くとエラーが出る。
  
  # ストロングパラメータ：マスアサインメント脆弱性を防ぐ仕組み
  # ※マスアサインメント脆弱性：悪意のあるユーザーが改竄したデータを保存してしまうシステムの弱さ。
  def list_params
    params.require(:list).permit(:title, :body, :image)
    # params:formからのデータが入るところ
    # require:送られたデータ中からモデル名を指定し（:list）、データを絞り込む
    # permit：絞り込んだデータから、保存を許可するカラムを指定
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fontsgoogleapis.com/css?family=Kaushan+script" rel="stylesheet">
  </head>

  <body>

    <header>
      <h1 class="headline"> All Lists </h1>
    </header>
  
    <nav>
      <ul class="nav-list">
        <li class="nav-list-item">
          <%= link_to "Top", top_path %>
        </li>
        <li class="nav-list-item">
          <%= link_to "lists", lists_path %>
        </li>
        <li class="nav-list-item">
          <%= link_to "New List", new_list_path %>
        </li>
      </ul>
    </nav>

    <main>
      <%= yield %>
    </main>

  </body>
</html>

app/views/lists/edit.html.erb
<h1>編集画面</h1>

<%= form_with model: @list do |f| %>
  <!-- form_withの詳細はnew.html.erb参照 -->

    <h4>タイトル</h4>
    <%= f.text_field :title %>

    <h4>本文</h4>
    <%= f.text_area :body %>

    <h4>画像</h4>
    <%= f.file_field :image, accept: "image/*" %>

    <p></p>
    <%= f.submit '保存' %>

<% end %>

app/views/lists/index.html.erb
<div class="list-wrap">
<% @lists.each do |list| %>
    <div class="list-box">
        <% if list.image.attached? %>
            <%= image_tag list.image, size: "200x200" %>
        <% else %>
            <%= image_tag 'no-image', size: "200x200" %>
        <% end %>
        <div class="list-comment">
            <span class="list-body"><%= list.body %></span>
            <span class="list-title"><%= link_to list.title, list_path(list.id) %></span>
        </div>
    </div>
<% end %>
</div>
    







<!-- ～9章のコード -->
<!-- <h1>投稿一覧</h1> -->

<!--<% @lists.each do |list| %>-->
<!-- レコードの数だけ繰り返し処理を行う -->
<!-- HTMLとして表示しないようにするため=はつけない -->

   <!-- <p>タイトル</p> -->
   <!-- <span>-->
        <!-- リンク設定 link_to 表示テキスト, リンク先URL[オプション] -->
        <!--<%= link_to list.title, list_path(list.id) %>-->
            <!-- path:特定のURLのパスを指すルーティング -->
   <!--</span>-->

   <!--<p>画像</p>-->
    <!-- imageが添付されていればimage、なければno_image.jpgが表示される。-->
    <!-- ⇒validation追加にて削除、画像が存在しない場合の処理が不要のため、以下追加 -->
    <!--<%= image_tag list.image, size: "200x200" %>-->
<!--<% end %>-->

app/views/lists/new.html.erb
<h1>新規投稿</h1>

<!-- %= %：HTMLに変換する、動的なコンテンツとして表示（変化）-->
<!-- % %：HTMLに変換しない、静的なコンテンツとして表示（不変） -->

<!-- validation時のエラーメッセージ表示 -->
<% if @list.errors.any? %>
<!-- any?でエラーが発生しているかどうかを判断 -->
    <%= @list.errors.count %> 件のエラーが発生しました
<!-- エラーメッセージのリスト(Unordered list（順序無しリスト）) -->
    <ul>
        <% @list.errors.full_messages.each do |message| %>
        <!--full_messagesでエラー内容の出力、エラー文が配列で保存されているためeach -->
            <li><%= message %></li>
        <% end %>
    </ul>
<% end %>

<%= form_with model: @list, url: '/lists', method: :post do |f| %>
 <!-- url:どのURLへ送信するか method:HTTPメソッドを指定 -->
    <h4>タイトル</h4>
    <%= f.text_field :title %>

    <h4>本文</h4>
    <%= f.text_area :body %>

    <h4>画像</h4>
    <%= f.file_field :image, accept: "image/*" %>

    <p></p>
    <%= f.submit '投稿' %>
<% end %>

<!-- form_with補足 -->
<!-- table（表）タグ直下、tr（行）タグ直下はformが上手く機能しない場合がある。 -->

app/views/lists/show.html.erb
<h2>タイトル</h2>
<p><%= @list.title %></p>

<h2>本文</h2>
<p><%= @list.body %></p>

<h2>画像</h2>
<!-- validation追加にてif削除。画像が存在しない場合の処理が不要のため、以下追加 -->
<%= image_tag @list.image, size: "300x300" %>

<p></p>
<%= link_to "編集", edit_list_path(@list.id) %>
<%= link_to "削除", list_path(@list.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
<!-- destroyアクションのHTTPメソッドはdelete -->
<!-- deta-confirmで削除確認ダイアログを表示 -->